### ISSUE TITLE
Run times?

### ISSUE THREAD

**Issue by melnel000** [eol017/CNV-Z#2]
Hi

Thanks for the great tool. I am trying it out and wondering about the run times. I am testing on 8 exome samples and I am not seeing any output written to the mosdepth files, nor am I getting any error messages:

julia -t 32 CNV-Z.jl IC_SGS_00077 IC_SGS_00002 IC_SGS_00013 IC_SGS_00019 IC_SGS_00027 IC_SGS_00034 IC_SGS_00043 IC_SGS_00049
["IC_SGS_00077", "IC_SGS_00002", "IC_SGS_00013", "IC_SGS_00019", "IC_SGS_00027", "IC_SGS_00034", "IC_SGS_00043", "IC_SGS_00049"]

0 Jan  8 21:19 mdepth-IC_SGS_00002.txt
0 Jan  8 21:19 mdepth-IC_SGS_00013.txt
0 Jan  8 21:19 mdepth-IC_SGS_00019.txt
0 Jan  8 21:19 mdepth-IC_SGS_00027.txt
0 Jan  8 21:19 mdepth-IC_SGS_00034.txt
0 Jan  8 21:19 mdepth-IC_SGS_00043.txt
0 Jan  8 21:19 mdepth-IC_SGS_00049.txt
0 Jan  8 21:19 mdepth-IC_SGS_00077.txt

Thanks, Melissa.

**Comment by eol017** [comment]
Hi Melissa,

First of all, there is no point in adding more threads than the number of samples included because run time can be approximated by the time taken for samtools depth to process one sample provided the number of threads equals the number of samples included. Thus, the run time depends on the size of the bed file and also on the number of threads available. The rest of the program is very fast and usually completes within a minute even if ~100 samples are included. 

Your output indicates that the calls to samtools depth have failed. 

First, the program will fail if for example your bam file IC_SGS_00077 is named anything else but IC_SGS_00077.sorted.bam. 

Second, check that the target bed file and your bam files are coordinate sorted and correspond as to the use of the prefix "chr" when naming chromosomes.

Third, open the copy of the CNV-Z.jl program you are using in a text editor e.g. VIM and replace “hglft_ICR96target.bed” (marked in red below) with the name (path) of your target bed file. If your sorted bam files are named with another pattern than “<sampleID>.sorted .bam” the yellow highlighted text on line 10 should also be altered according to your naming pattern. 
_____________________________________________________________

#Usage: julia -t 8 CNV-Z.jl <sampleID> [<sampleID> <sampleID> ... ]
#Adjust the number of threads, and paths to targets and bamfiles below if necessary

using CSV, DataFrames, Statistics, Base.Threads

println(ARGS)

Threads.@threads for i in ARGS
	open("mdepth-$i.txt","w") do io
		write(io,read(`samtools depth -a -b hglft_ICR96target.bed $i.sorted.bam`))
	end
end

for i in ARGS
	open("mdepth-$i.h.txt","w") do io
		write(io,read(`cat header.txt mdepth-$i.txt`))
	end
end
…
_____________________________________________________________________________

This should work,
Emma
